name: linkedin-auto-blogger

on:
  schedule:
    - cron: '0 12 * * *'   # 08:00 Toronto (EDT) daily
    - cron: '0 17 * * *'   # 13:00 Toronto (EDT) daily
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 370
    env:
      TIMEZONE: America/Toronto
      TOPICS_CSV: content/topics.csv
      CRON_SCHEDULE: ${{ github.event.schedule }}
      LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
      LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
      LINKEDIN_REFRESH_TOKEN: ${{ secrets.LINKEDIN_REFRESH_TOKEN }}
      LINKEDIN_MEMBER_URN: ${{ secrets.LINKEDIN_MEMBER_URN }}
      NTFY_URL: https://ntfy.sh
      NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
      LINKEDIN_VERSION: '202507'
      # Optional: allow either window on the anchor day for a predictable first post
      # ALLOW_BOTH_WINDOWS_FIRST_DAY: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Sanity check
        run: |
          echo "TOPICS_CSV=$TOPICS_CSV"
          ls -la
          test -f "$TOPICS_CSV" || (echo "❌ Missing $TOPICS_CSV"; exit 1)
          head -n 2 "$TOPICS_CSV"

      # Normal automated behaviour for scheduled runs
      - name: Run auto-poster (scheduled)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: python scripts/run.py

      # Immediate post for manual tests (skips cadence & waiting)
      - name: Run auto-poster (manual force)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          FORCE_POST: "1"
        run: python scripts/run.py
